name: 'Conventionnal commit PR labeler'
description: 'Labels PR with conventional commit'
author: 'Stephdotnet'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  token:
    description: 'Github token'
    required: true

runs:
  using: node20
  main: dist/index.js
